Elastic library upgrade
huridocs/uwazi pull request #3206
Opened 2020-09-24 08:28 UTC by konzz

fixes #

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2020-09-24 17:12 UTC, RafaPolit commented on app/api/search/search.js
> +      })
This is yielding a warning, and it looks like it was intercepted to do some debugging, but it should be reverted to the arrow function directly returning the processResponse as the warning suggests.

2020-09-24 17:14 UTC, RafaPolit commented
This PR should also include an update of the README.  I understand this is NOT backwards compatible with 7.6, right?
Should we include checks on our Server.js to report Node, Mongo and ElasticSearch versions?

2020-09-24 19:21 UTC, txau commented
> This PR should also include an update of the README. I understand this is NOT backwards compatible with 7.6, right?
> Should we include checks on our Server.js to report Node, Mongo and ElasticSearch versions?

It needs some README update. But it may be compatible with previous versions. I hope @konzz can confirm.

2020-09-24 19:25 UTC, txau commented
For this PR:
- Is it confirmed that we don't need the --max-http-header-size 20000 flag anymore?
- Recover the ICU part for the README
- Confirm if this module is backwards compatible with Elastic 7.6
- Make sure our CI scripts are using ES 7.9.1

2020-09-25 11:24 UTC, konzz commented
I didn't upgrade elastic to 7.9
This PR is just "Elastic library upgrade" as the title says, but if you want I can also check this with elastic 7.9 and add that to the PR.

2020-09-28 15:59 UTC, RafaPolit requested changes

2020-09-28 15:59 UTC, RafaPolit commented on README.md
> +- **ElasticSearch 7.9.1** https://www.elastic.co/guide/en/elasticsearch/reference/7.6/install-elasticsearch.html Please note that ElasticSearch requires java. Follow the instructions to instal the pa
The link needs to be updated as well, it reads /7.6/

2020-09-28 22:08 UTC, txau commented
LGTM. Too bad the header overflow error is still present. I guess we have to live with the CLI flag for now.

2020-09-29 12:15 UTC, merged