2899 closing mobile filtering
huridocs/uwazi pull request #3239
Opened 2020-10-07 20:10 UTC by mfacar

fixes #2899

This PR includes:
- [ ] X button on filters sidepanel on mobile view from library
- [ ]  Replace search icon with filter on mobile header

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2020-10-13 13:30 UTC, konzz commented
LGTM, resolve the conflicts

2020-10-13 15:36 UTC, mfacar commented
> LGTM, resolve the conflicts

done :)

2020-10-14 13:41 UTC, RafaPolit commented
Please, check the breakpoint:

Sidepanel breakpoint from collapsible to always-visible is 1023px, not 769px.  I don't know how this value became the standard, but you cannot close the sidepanel from 769 to 1023 with this approach.

Also, this is not working on iOS.

The side bar is not positioned on top of navbar, but rather underneath, making it impossible to click on the X.

Also, using in mobile iOS, the "close" arrow is correctly present on the header replacing the "search" button (now the funnel).  So, either:
- ensure that the side panel is on top of the nav bar, or
- move the sidepanel on mobile below the nav bar

2020-10-14 13:44 UTC, RafaPolit requested changes

2020-10-14 13:44 UTC, RafaPolit commented on app/react/App/scss/layout/_sidepanel.scss
> +  @media (min-width: 769px) {
This breakpoint leaves from 769 to 1023 without the option to close the sidepanel.

2020-10-16 02:04 UTC, mfacar commented
> Also, using in mobile iOS, the "close" arrow was correctly present on the header replacing the "search" button (now the funnel), which is no longer the case. So, either:
> 
> * ensure that the side panel is on top of the nav bar, or
> * move the sidepanel on mobile below the nav bar

I have applied the first option, iOS evidenced a problem with the overflow of the class library-viewer, it's fixed now.

2020-11-24 03:46 UTC, RafaPolit commented
LGTM

2020-11-24 03:46 UTC, merged