3494 media field revamp
huridocs/uwazi pull request #3524
Opened 2021-03-16 14:02 UTC by konzz

fixes #3494

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2021-03-30 23:24 UTC, mfacar requested changes
@konzz, @vkozinec, @yacky, Nice job! the code looks pretty nice, I just left some comments about small things.

Regarding the Functional Review:
* @konzz can you please specify the scope of the PR, maybe updating the related issue?. 
* I just tested the edition and visualization of entity properties with type image/media, which I think are the first and second points of issue #3494 still with the URL as the value of the property.  These functionalities are working pretty well.
* I only found two minor issues of UI on `Add form url tab`
   - Information icon doesn’t show any hint
   - The label of the button should be `Add Resource` according to the design.

2021-03-30 23:26 UTC, mfacar commented
Also, please can you take a look at the Code Climate issues?  Probably some of them could be solved.

2021-04-01 06:40 UTC, konzz commented on app/react/Attachments/components/specs/RenderAttachment.spec.tsx
> +        jest.spyOn(ReactPlayer, 'canPlay').mockReturnValue(true);
it is the first one that says "unsuported scenarios"

2021-04-01 06:47 UTC, konzz commented on app/react/Documents/components/DocumentSidePanel.js
> +                        storeKey={this.props.storeKey}
wow, good one

2021-04-01 06:57 UTC, konzz commented on app/react/Metadata/components/specs/MediaModal.spec.tsx
> +    const attachments = component.find('.media-grid-item');
done

2021-04-01 06:59 UTC, konzz commented on nightmare/suite1/metadataprops.spec.js
> +        multiselect;
fixed

2021-04-01 06:59 UTC, konzz commented on app/react/Metadata/containers/FormatMetadata.js
> +  attachments: PropTypes.arrayOf(PropTypes.object),
yes it wasnt, it was from previous implementation

2021-04-01 07:00 UTC, konzz commented on app/react/Metadata/components/specs/MediaModal.spec.tsx
> +    expect(attachments.length).toBe(1);
changed the specs so it expect the correct attachment been used

2021-04-01 07:03 UTC, konzz commented on app/react/Metadata/components/specs/MediaModal.spec.tsx
> +    expect(props.onClose).toHaveBeenCalled();
yes, added that check

2021-04-01 10:02 UTC, vkozinec commented on app/react/App/scss/modules/_attachments-modal.scss
> +        max-width: calc(100% + 20px) !important;
We can remove it from here, but we need it few lines down since I need to fit existing component there that renders video, so it has to be there.

2021-04-06 09:38 UTC, yacky commented on app/react/Metadata/components/MediaModal.tsx
> +  url: { required: (val: any) => !!val && val.trim() !== '' },
No, this can only be string. It's fixed now.

2021-04-06 09:39 UTC, yacky commented on app/react/Metadata/components/MediaModal.tsx
> +                      const attachmentUrl = attachment.url || `/api/files/${attachment.filename}`;
We have 2 tests that check for url that is sent on `onChange` prop. First one is checking attachment with filename, second attachment with url.

2021-04-06 09:40 UTC, yacky commented on app/react/Metadata/components/MediaModal.tsx
> +                <LocalForm
We now have test for web attachment.

2021-04-07 01:02 UTC, mfacar approved these changes
LGTM, I'll merge the PR as soon as the fixes for the `from the web` tab be ready

2021-04-07 14:10 UTC, merged