3579 entity id generator field
huridocs/uwazi pull request #3595
Opened 2021-04-12 21:16 UTC by mfacar

fixes #3579

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2021-04-27 22:30 UTC, fnocetti requested changes
@mfacar if this approach is the correct, then it LGTM but for a couple of comments. Let's present it to the team.
I still need to test this, on the while, please, take a look :)

2021-04-28 01:14 UTC, mfacar commented on app/react/Metadata/actions/actions.js
> +      if (defaultValue !== undefined) resetedMetadata[name] = defaultValue;
No, it is not enough, there are some types that have as a valid default value an empty string.

2021-04-28 01:16 UTC, mfacar commented on app/shared/IDGenerator.ts
> +const IDGenerator = {
No reason, I'll change it

2021-04-28 16:44 UTC, fnocetti commented on app/react/Metadata/actions/actions.js
> +      if (defaultValue !== undefined) resetedMetadata[name] = defaultValue;
Gotcha!

2021-04-29 20:58 UTC, fnocetti commented
@mfacar The functionality looks good en general. There's two bugs:

- When using the ID field as a filter it doesn't work. It's not filtering and also shows [object Object] as in the image bellow when blank.

<img width="387" alt="Screen Shot 2021-04-29 at 5 42 26 PM" src="https://user-images.githubusercontent.com/11740873/116615884-5249b600-a912-11eb-9eaf-1adcb3f7d3dc.png">

- CSV import is not generating the value. Used the following csv on the Document template (default):

`title,generated id
con, GENID
sin,`

The first one is taking the provided value while the second is staying empty.

Please check. Thanks!

2021-04-30 00:51 UTC, mfacar commented
Good catches, thank you Fede, I'm working on them

2021-05-04 02:45 UTC, mfacar commented
@fnocetti, the bugs are fixed, thanks for reporting them. I found a problem at the searching by this type of property which is also fixed. Please take a look.

2021-05-06 21:13 UTC, fnocetti approved these changes
Looks good! Good job! Merging now

2021-05-06 21:13 UTC, merged