Remove unwanted  FABs
huridocs/uwazi pull request #3599
Opened 2021-04-14 16:28 UTC by grafitto

fixes #3186 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2021-04-16 16:52 UTC, fnocetti requested changes
In general it LGTM. Please check the comments.

2021-04-16 16:52 UTC, fnocetti commented on nightmare/helpers/selectors.js
> +      '#app > div.content > div > div > div > aside.side-panel.library-filters > div.sidepanel-body > div > ul > li:nth-child(2) > label', //.documentTypes-selector.nested-selector
Please remove comment

2021-04-16 16:52 UTC, fnocetti commented on nightmare/helpers/selectors.js
> +    // '#app > div.content > header > ul > li.menuActions > ul > li:nth-child(1) > a',
Remove comment here as well

2021-04-16 17:59 UTC, fnocetti commented
The testing went just OK. I'll wait for the changes to merge.

2021-04-19 10:29 UTC, grafitto commented on nightmare/helpers/selectors.js
> +    // '#app > div.content > header > ul > li.menuActions > ul > li:nth-child(1) > a',
Done

2021-04-19 13:20 UTC, RafaPolit commented on app/react/App/scss/layout/_sidepanel.scss
> +    }
Please indent this correctly.

2021-04-19 13:29 UTC, RafaPolit commented
I am sorry if this comes late, but this design is not useful without having the filter title being a sticky.  In order to reset filters on a very long list you would need to scroll back up to the title.  The precise reason the reset button was made a fab.

@simonfossom was this the intended behavior?

2021-04-19 13:31 UTC, RafaPolit requested changes
I have commented about the scrolling issue, please do not merge this without confirming design problems.

2021-04-19 15:37 UTC, fnocetti commented
@RafaPolit noted. That's a fair point.

2021-04-19 16:59 UTC, simonfossom commented
> I am sorry if this comes late, but this design is not useful without having the filter title being a sticky. In order to reset filters on a very long list you would need to scroll back up to the title. The precise reason the reset button was made a fab.
> 
> @simonfossom was this the intended behavior?

I understand the concern but how many filters should there be before quick scroll to the top is a problem?
Another argument is that clearing filters is secondary action to selecting filters. With that rational all filters should always be in view. 
Yet another argument would be that already short hight of filter panel would be even shorter (which is also one of the reasons why FABs are a problem.).

I don't know. What's the reason for having it always visible? I couldn't find any instance where I needed to scroll more than once to reach the top of filters.

2021-04-20 12:19 UTC, nwyu commented
Fair point raised by @RafaPolit, but @grafitto let's proceed as it is designed. Please ensure, as well, that the Clear Filters button is next to the x on mobile.

2021-04-20 13:26 UTC, fnocetti commented
@nwyu ok, this is noted. I'll finish the QA and merge this as it is
cc @RafaPolit

2021-04-20 13:52 UTC, grafitto commented on app/react/App/scss/layout/_sidepanel.scss
> +    }
Done

2021-04-20 14:19 UTC, grafitto commented
> Fair point raised by @RafaPolit, but @grafitto let's proceed as it is designed. Please ensure, as well, that the Clear Filters button is next to the x on mobile.

Yes it is.

2021-04-20 14:22 UTC, merged