Consider public type in activity log
huridocs/uwazi pull request #3621
Opened 2021-04-21 19:48 UTC by fnocetti

fixes #3615

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2021-04-23 13:43 UTC, daneryl requested changes
@fnocetti all good, there is a minor issue with the message generated. if you only add the public group to an entity or multiple entities, the activity log message reads as follows:

```with permissions for; and PUBLIC```

2021-04-23 13:45 UTC, fnocetti commented
> @fnocetti all good, there is a minor issue with the message generated. if you only add the public group to an entity or multiple entities, the activity log message reads as follows:
> 
> `with permissions for; and PUBLIC`

Good one. I'll fix it.

2021-04-23 16:50 UTC, fnocetti commented
@daneryl so I basically removed the "and" since there were none before this change. Please review.

2021-04-26 13:13 UTC, daneryl approved these changes

2021-04-26 13:14 UTC, merged