435 suggest url based on heading
huridocs/uwazi pull request #3719
Opened 2021-06-02 09:03 UTC by vkozinec

fixes #435 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2021-06-11 19:30 UTC, fnocetti requested changes
Hi @vkozinec ! Thank you for the PR and please excuse the delay in the review.
The code looks good and the implementation runs as expected.
I left one comment that I'd appreciate you to take a look. Also there's an e2e failing in the puppeteer suite. Could you please take a look?

Please let us know if you need any assistance. Thanks!

2021-06-15 08:26 UTC, ivan-init commented on app/react/Pages/components/PageCreator.tsx
> +import _ from 'lodash';
@fnocetti Lodash is now installed as a dependency and e2e tests are fixed

2021-06-15 08:29 UTC, yacky commented on app/react/Pages/components/PageCreator.tsx
> +import _ from 'lodash';
@fnocetti Lodash is now installed as a dependency and e2e tests are fixed

2021-06-15 13:56 UTC, fnocetti commented on app/react/Pages/components/PageCreator.tsx
> +import _ from 'lodash';
Thanks @yacky, I'll take a look!

2021-06-21 21:06 UTC, fnocetti approved these changes
LGTM

2021-06-21 21:06 UTC, merged