inherit filters and aggregations
huridocs/uwazi pull request #3747
Opened 2021-06-16 13:49 UTC by daneryl

- filter by inheritedValue
- deleted component for removed filter
- Search Filters showing the proper filter for the inherited property
- search using inherited type when generating elastic search filters and aggregations
- removed fit
- Correct content when aggregating an inherited dictionary with groups
- added id to property in fixtures to fix an spec
- added id to fixtures to fix spec
- removed focused test
- fixed some eslin t errors
- fixed eslint destructuring errors
- abstract method get inherited property
- using template selector
- minor fixes
- WIP, denormalize inherit type
- Denormalization of inherited property type WIP
- remove inheritProperty in favor of inherit.property
- capture mapping error only, throw the rest
- Migration to denormalize inherit type
- Template form adapt to new inherit structure
- babel-eslint version to match babel-core
- checkMapping tests for inheritValue
- Client refactor from inheritProperty to inherit.property
- fixed error in FormConfigRelationship when relationship property is not inheriting
- checkMapping tests for inheritValue
- better handling of mapping error
- remove inherit property value when unselecting inherit in a property config
- fixed ts types
- fix babel/eslint-parser version
- fixed lints
- renamed migration to 42
- added raw field to markdown mapping to be able to tex filter by it
- branch stabilization

fixes #

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2021-06-30 07:04 UTC, konzz commented
Please also do QA for this issue #3783 to see if its fixed by this PR

2021-07-05 23:36 UTC, mfacar requested changes
@konzz it looks really good, I just left some minor comments on code.
I did several functional tests and all is working well, I think this PR is even solving #3739. I just have a concern regarding the options for inherited properties, shouldn't we restrict the filter and sorting options for properties of types images, preview, geolocations, in the same way that we are doing for the template properties? When I add for example an inherited image as a default filter, there is a text box that could be confusing for the user.

2021-07-06 00:27 UTC, mfacar commented
Just for the record, some behaviors I think are expected:
- Inheriting from the same value from two different related entities: the values are shown duplicated, probably noisier with images
<img width="96" alt="Screen Shot 2021-07-05 at 19 04 47" src="https://user-images.githubusercontent.com/5322716/124525342-92bb2980-ddc4-11eb-9da5-5a82b287cb24.png">

- Inheriting an inherited value: it shows a link for the inherited entities.
<img width="97" alt="Screen Shot 2021-07-05 at 19 17 06" src="https://user-images.githubusercontent.com/5322716/124525645-9bf8c600-ddc5-11eb-8613-d020722fb783.png">

2021-07-07 08:13 UTC, konzz commented on app/api/search/specs/entitiesIndex.spec.ts
> +      it('should throw the error', async () => {
Yes, not sure how the descriptions where swap. Fixed

2021-07-07 08:14 UTC, konzz commented on app/api/templates/specs/templateSchema.spec.ts
> +      it('invalid if different table with the same name already exists', async () => {
fixed

2021-07-08 06:37 UTC, konzz commented on database/elastic_mapping/elasticMapFactory.ts
> +            }
removed

2021-07-08 06:37 UTC, konzz commented on app/api/templates/utils.ts
> +    return indexed;
changed

2021-07-08 20:40 UTC, mfacar commented
@konzz, LGTM!, previous to merge it, please can you comment on the following items:
- I think this PR solves #3739 because it's preventing the error case but not sure if we should attach it here.
- Shouldn't we restrict the filter and sorting options for properties of types images, preview, geolocations, in the same way that we are doing for the template properties? When I add for example an inherited image as a default filter, there is a text box that could be confusing for the user.

2021-07-09 11:24 UTC, konzz commented
> * I think this PR solves [Inconsistent input type on sidepanel filter (13pts) #3739](https://github.com/huridocs/uwazi/issues/3739) because it's preventing the error case but not sure if we should attach it here.

yes, I added it to the PR fixes list, since that is the issue that triegered the rollback, not sure why it wasnt in the list.

> * Shouldn't we restrict the filter and sorting options for properties of types images, preview, geolocations, in the same way that we are doing for the template properties? When I add for example an inherited image as a default filter, there is a text box that could be confusing for the user.

I-m gona work in a solution for that.

2021-07-09 14:45 UTC, mfacar commented on app/api/search/entitiesIndex.js
> +    ]);
For the record, we decided to keep the mappingUpdate in both places given the validation doesn't ensure completely that won't have an error at template saving, we need to review it in the future.

2021-07-09 14:49 UTC, mfacar approved these changes

2021-07-09 15:14 UTC, mfacar commented on app/react/Templates/components/FormConfigRelationship.js
> +        !['image', 'markdown', 'preview', 'media', 'link'].includes(inheritSelectPropertyType));
I think it should be `geolocation` instead of `markdown` following the same behavior of regular properties.

2021-07-09 15:40 UTC, merged