3731 bulk share bottleneck
huridocs/uwazi pull request #3803
Opened 2021-07-09 07:31 UTC by LaszloKecskes

fixes #3731 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2021-07-10 02:20 UTC, mfacar requested changes
The code LGTM!, I left a couple of comments about minor things. I'll put the results of QA just after finishing the tests on the functionality

2021-07-12 02:36 UTC, mfacar commented
@LaszloKecskes, QA went pretty well, there's an important reduction in the response time, I think that this improvement can also be applied to the set method in `entitiesPermissions`. Although it's not part of this issue, please can you check it?

2021-07-12 07:16 UTC, LaszloKecskes commented on app/api/entities/entities.js
> +      : [];
That was what I've done first. It breaks a unittest in the search api, due to wrong indexing. What happens is:
1, Have entities that share documents.
2, During the indexing process [this function](https://github.com/huridocs/uwazi/blob/e95450312781d3ece88ac5a57fd4ae5a0aafa383/app/api/search/entitiesIndex.js#L45) is reached, which deletes the fullText from the js object representing the file.
3, If you pass the array (and the objects) directly, the js object will be shared between the entities.
4, The function deletes the fullText on the first entity that has the file.
5, On the second entity, it sees that there is no fullText, and bad information will be passed to elastic, breaking the indexing.

So, in this case, it is intentional that a copy is passed, not the original object. 

I have also thought about leaving a comment here, marking that this is intentional. Now, that you've find this, I think that's a good proof that that will be a necessary comment. :)

2021-07-12 07:24 UTC, LaszloKecskes commented on app/api/entities/specs/entities.spec.js
> +      }
Sure, will do so.

2021-07-12 14:07 UTC, mfacar commented on app/api/entities/entities.js
> +      : [];
Ohh, good to know, I think if a test is broken changing it, the comment it's not needed. I leave it to your decision :)

2021-07-12 16:10 UTC, mfacar commented
> @LaszloKecskes, QA went pretty well, there's an important reduction in the response time, I think that this improvement can also be applied to the set method in `entitiesPermissions`. Although it's not part of this issue, please can you check it?

The team decided to open a new issue (#3804) to tackle this.

2021-07-12 16:11 UTC, mfacar approved these changes

2021-07-12 16:11 UTC, merged