3801 - Mark document properties
huridocs/uwazi pull request #3847
Opened 2021-08-02 13:24 UTC by Zasa-san

fixes #3801

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2021-08-24 09:30 UTC, gabriel-piles commented
This feature rocks, good job.

There are few issues though:

* When there are multiple PDFs in one entity, all the "click to fill" from the different PDFs are stored in the main PDF.
* When there are multiple languages, all the "click to fill" are stored in MongoDB without the language information so it is difficult to know in which language was the "click to fill".
* When there is an entity with a property filled with "click to fill" and the property name is changed in the template settings, the entity could not be edited anymore.

2021-08-24 21:30 UTC, fnocetti requested changes
@Zasa-san this is an awesome work. I left some comments. Please take a look. Thanks!

2021-08-24 21:30 UTC, fnocetti commented on app/api/entities/metadataExtraction/saveSelections.ts
> +    title: entity.title,
This might give problems if some database has a template with a field called `Title`. Idk if it's worth fixing.

2021-08-25 12:50 UTC, Zasa-san commented on app/react/Metadata/components/MetadataForm.js
> +          <>
I think not! I'll remove it!

2021-09-02 10:21 UTC, gabriel-piles commented
Looks good to me.

2021-09-06 20:42 UTC, fnocetti approved these changes
LGTM, good job!

2021-09-06 20:42 UTC, fnocetti commented
Merging as discussed with @gabriel-piles

2021-09-06 20:42 UTC, merged