3764 import nested thesaurus
huridocs/uwazi pull request #4098
Opened 2021-12-18 01:31 UTC by mfacar

fixes #3764

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2021-12-21 18:00 UTC, fnocetti requested changes
This LGTM. I just left a couple of not-that-important comments.
I'm proceeding to the testing now.

2021-12-21 18:43 UTC, fnocetti commented
@mfacar Everything seems to work nicely, except for the following issue:
If in the CSV file you put the label for a thesauri group (or root thesauri) it is correctly imported, and shown in the cards. When you go to the entity view or to entity edit, the value is not rendered.
You should only be allowed to select leaf thesauri values, right?

2021-12-21 20:27 UTC, mfacar commented
> @mfacar Everything seems to work nicely, except for the following issue: If in the CSV file you put the label for a thesauri group (or root thesauri) it is correctly imported, and shown in the cards. When you go to the entity view or to entity edit, the value is not rendered. You should only be allowed to select leaf thesauri values, right?

That's right, however probably it should be a new issue, because it's also happening at sending the value through the API. I'll take a look here and add the solution if it's straightforward.

2021-12-22 02:35 UTC, mfacar commented on app/api/entities/validation/validateMetadataField.ts
> +  const thesaurusValues = _.flatMapDeep(thesaurus?.values, tv =>
done

2021-12-22 02:35 UTC, mfacar commented on app/api/csv/specs/csvLoaderSelects.spec.js
> +    it('should only add as new values those which are not nested values', async () => {
done

2021-12-22 14:26 UTC, fnocetti approved these changes
LGTM!

2021-12-22 19:07 UTC, merged